export {default as Calculate} from './calculate'
export {default as Info} from './info'
export {default as Diagrams} from './diagram'
export {default as FilterCalculate} from './filter-calculate'
export {default as Gallery} from './gallery'